### ISSUE TITLE
missing for music data

### ISSUE THREAD

**Issue by YeMeng12** [google/aistplusplus_api#12]
In the dataset "aist_plusplus_final", the music data is missed.  If I want to start my task that focus on  music conditioned motion generation, maybe the AIST++ can't be used.

**Comment by liruilong940607** [comment]
You can either acquire the music by downloading all the videos using our ‘downloaded.py’ or directly download the music from the AIST dance database website here: 
https://aistdancedb.ongaaccel.jp/database_download/
