### ISSUE TITLE
Question about visualizing the SMPL joints

### ISSUE THREAD

**Issue by zsh2000** [google/aistplusplus_api#16]
Hi,

Your work is excellent and I am interested in it! Now I'm trying my hands on visualizing the SMPL joints. 

But I have no idea about where the file "SMPL_MALE.pkl" is and what function it serves as. Could you please tell me about it?

Sincerely,
Shuhong

**Comment by Jhc-china** [comment]
I download the SMPL model file from [https://smpl.is.tue.mpg.de/downloads](url), and rename the pkl model file to "SMPL_MALE.pkl" and "SMPL_FEMALE.pkl" respectively. I think the pkl file is used to initialize SMPL model (defined in [https://github.com/liruilong940607/smplx](url)), which is slightly modified from original SMPL codes.

**Comment by zsh2000** [comment]
> I download the SMPL model file from [https://smpl.is.tue.mpg.de/downloads](url), and rename the pkl model file to "SMPL_MALE.pkl" and "SMPL_FEMALE.pkl" respectively. I think the pkl file is used to initialize SMPL model (defined in [https://github.com/liruilong940607/smplx](url)), which is slightly modified from original SMPL codes.

Thank you so much! It really solved my problem!

**Comment by zsh2000** [comment]
Sorry for bothering you again. 

Now I want to visualize the SMPL Mesh. I come across a "segmentation fault (core dump)" when running the line 
> `vedo.show(mesh, pts, interactive=True)`

I don't know whether it's the problem of the python library "vedo" or any problems else.

**Comment by Humoon** [comment]
> I download the SMPL model file from [https://smpl.is.tue.mpg.de/downloads](url), and rename the pkl model file to "SMPL_MALE.pkl" and "SMPL_FEMALE.pkl" respectively. I think the pkl file is used to initialize SMPL model (defined in [https://github.com/liruilong940607/smplx](url)), which is slightly modified from original SMPL codes.

Thank you very much for your reply! 

I did not find the download button of SMPL model on the download page. Then I downloaded other files on this web page, but did not find the "SMPL_MALE.pkl" and "SMPL_FEMALE.pkl".

Is the download button of SMPL model cancelled？

Thanks again🙏

**Comment by LinghaoChan** [comment]
> Sorry for bothering you again.
> 
> Now I want to visualize the SMPL Mesh. I come across a "segmentation fault (core dump)" when running the line
> 
> > `vedo.show(mesh, pts, interactive=True)`
> 
> I don't know whether it's the problem of the python library "vedo" or any problems else.

Have you resolved this problem? I met with the same problem.
