### ISSUE TITLE
question about initial f value in camera estimation

### ISSUE THREAD

**Issue by zenithfang** [google/aistplusplus_api#18]
Could you tell me why do you choose 1600 as initial f for camera intrinsics? Does this value influence the result importantly? I would really appreciate your response

**Comment by liruilong940607** [comment]
Sorry for the late response. This is a manually selected value by try-and-error. For bundle adjustment to work it needs to have a relatively good initialization. But it's not that strict. The focal length after bundle adjustment is around 1500, which means ~100 error is tolerable.
