### ISSUE TITLE
Trouble downloading the dataset

### ISSUE THREAD

**Issue by AmberCheng** [google/aistplusplus_api#2]
Hi，

Thanks for your. wonderful datasets.

I recently do some thing about 3D humane pose and I tried to download your dataset. However I always meet the error 'multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f344db94160>'. Reason: 'TypeError("cannot serialize '_io.BufferedReader' object",)'. 

Thus I am not sure whether I have finished the downloading. I find a video file list in downloader.py, so I download it individually. I find the video_list contains 12669 items, but it not equal to the annotations which only contains 1408 SMPL files. 

I wonder how to check the dataset? One more thing, how can I fixed the error  when I using?

Looking forward to hearing from you,

**Comment by Realdr4g0n** [comment]
I was occured this error too

and so I download it individually. but download speed is terrible.

How can I download stable and faseter than 10KB/s

**Comment by AmberCheng** [comment]
> I was occured this error too
> 
> and so I download it individually. but download speed is terrible.
> 
> How can I download stable and faseter than 10KB/s

**Comment by liruilong940607** [comment]
In my experience this error might cause by the unstable multiprocessing packge in lower python version. I recommand you to run `downloader.py` with `python=3.7` or `python=3.8`, which have been tested. 

Welcome to file this bug with your system environment so that we can track and fix it.

@AmberCheng Each of our annotation files correspond to several multi-view videos, so 1408 SMPL files contain annotations for all videos in the video_list.

**Comment by j-min** [comment]
@liruilong940607 Could you please let me know your download environment?
I tried Anaconda Python 3.6/3.7/3.8
```
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0] on linux
Python 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] :: Anaconda, Inc. on linux
Python 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0] :: Anaconda, Inc. on linux
```
but faced the same multiprocessing error.

I also tried single-process downloading, but faced the `HTTP Error 504: Gateway Time-out` from `urllib.request.urlretrieve(video_url, save_path)`.

**Comment by liruilong940607** [comment]
I just tested with my python 3.7.11 within conda environment on linux and it works with 2 processes. So I suspect maybe it's the connection issue of your linux machine? 

Could you download the individual mp4 using `wget` ?
