### ISSUE TITLE
video gLO_sBM_c01_d13_mLO1_ch09.mp4 download failed

### ISSUE THREAD

**Issue by prozyy** [google/aistplusplus_api#21]
file URL https://s3.abci.ai/aistdancedb.ongaaccel.jp/v1.0.0/video/10M/gLO_sBM_c01_d13_mLO1_ch09.mp4
downoad failed，How to get the video file ?

**Comment by liruilong940607** [comment]
Hi, we don't host the raw AIST videos so if there are some links somehow expired, you will have to contact the AIST people directly. For this video you posted I can successfully download it so I guess it is not a problem anymore.
