### ISSUE TITLE
Problem of rendering SMPL mesh

### ISSUE THREAD

**Issue by lioo717** [google/aistplusplus_api#22]
Thanks for your great job.
I have trouble when rendering the SMPL mesh. could you share the renderer code?
Thanks.

**Comment by liruilong940607** [comment]
Hi, you can check out the readme here for mesh visualization:
https://github.com/google/aistplusplus_api#visualize-the-smpl-mesh

**Comment by lioo717** [comment]
Sorry for bothering you again. Maybe I didn't describe the problem clearly. The problem is how to render the mesh matching the original image. Something like this:[https://github.com/mkocabas/VIBE/blob/master/doc/assets/parkour.gif](url)

**Comment by liruilong940607** [comment]
Hi, we rendered the mesh in blender so we don't have a script to attach it onto the image. I suggest you check out other repos that work on SMPL data such as [VIBE](https://github.com/mkocabas/VIBE) or HMR(https://github.com/akanazawa/hmr). There should be many resources that you can find on github. Besides, pytorch3d is also a nice choice to render a mesh.

**Comment by lioo717** [comment]
Thanks very much.
I'll try it.
