### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by cassanelligiovanni** [google/aistplusplus_api#23]
I Downloaded the Keypoints 3D only and it says "all annotations are 60 fps", however when i open them they seems to be 30fps for example a motion of duration : 1 minute and 35 seconds  is around 2800 frames not 5600 is it right ? should i treat the keypoints3d as 30fps.

Plus: if it is so and i want to extract audio_features with the same fps from audio, is it right to use a `sample rate = 48000 `and `hope_size = 800` ?

**Comment by liruilong940607** [comment]
I randomly checked a few and didn't find a motion sequence annotation with less than 60 fps. 

Would you please provide the sequence name that you find have less frames?

**Comment by cassanelligiovanni** [comment]
for example the following keypoint3d annotation :
`gJS_sFM_cAll_d02_mJS0_ch08.pkl`
is 2878 frames which at 60fps is supposed to be 47 second while the actual video last 1:35 minutes (double it), so i assumed that they are sampled at 30fps.

**Comment by liruilong940607** [comment]
I don't get where the 1:35 mins comes from. The actual video for that one is 47 secs long (link [here](https://s3.abci.ai/aistdancedb.ongaaccel.jp/v1.0.0/video/10M/gJS_sFM_c01_d02_mJS0_ch08.mp4)).

**Comment by cassanelligiovanni** [comment]
Oh my god, so sorry... I was converting from the videos to .mp3 with ffmpeg and i don't why it is looping the audio twice from 47 to 1:35. Thanks so much, that is surely a reason why my model was not converging
