### ISSUE TITLE
can't find SMPL download link

### ISSUE THREAD

**Issue by Humoon** [google/aistplusplus_api#26]
I can't find the download button of SMPL model on the download page of https://smpl.is.tue.mpg.de/downloads.

Is the download button of SMPL model has been cancelled？

Thanks!

**Comment by liruilong940607** [comment]
Hi, you would need to first register an account on the SMPL website. I believe the download page will show up after signing in.

**Comment by zhangsanfeng86** [comment]
@liruilong940607  Thank you for release codes.
But after signing in,  there is no download link.
![image](https://user-images.githubusercontent.com/73547638/160644984-170c9f56-8284-456a-bf10-b00dbd7b0367.png)

**Comment by liruilong940607** [comment]
the entrance for the download page is at the right corner right besides FAQ
