### ISSUE TITLE
Can not run the code of `Visualize the SMPL Mesh`

### ISSUE THREAD

**Issue by hatoriMain** [google/aistplusplus_api#27]
I'm trying to run the code of `visualize the smpl mesh` but it failed and here is the error. 
Would you please tell me why it doesn't work? Thanks.

![image](https://user-images.githubusercontent.com/51203739/135030196-bfd42751-4828-4aed-88ae-da4602105ecb.png)

**Comment by liruilong940607** [comment]
This visualization only works with local machines. It will pop up a window to show. It does not support running on the remote server without GUI.
