### ISSUE TITLE
How to visualize the generated dance motion with the API?

### ISSUE THREAD

**Issue by hatoriMain** [google/aistplusplus_api#29]
Hi ruilong, I'm trying the visualize the test result from the trained MINT model, I try to run the following demo code and the output is a freezing image like below. 
![image](https://user-images.githubusercontent.com/51203739/136740392-9e6c7304-c242-41ce-8bf3-cd26532517db.png)

![image](https://user-images.githubusercontent.com/51203739/136740182-f538b3ec-6ee8-43bb-99bf-ce76c8b56b51.png)

Could you tell me is there a code to visualize(render) the generated dance output to a video like the videos provided in the`overview of AIST++`? Thank you so much.

![image](https://user-images.githubusercontent.com/51203739/136740747-e7c3dd43-bf60-47e4-913f-bf3d19a28acd.png)

**Comment by liruilong940607** [comment]
Hi!
The API by default only visualize the first frame on the mesh to allow user interaction (rotating etc). Please check the code here: https://github.com/google/aistplusplus_api/blob/5a20b5f193c5b279461f9e123aa5c1fe6ec7c736/demos/run_vis.py#L96-L110

The easiest way to visualize the whole sequence is to do a for loop like this:
```
vertices = smpl.forward(
    global_orient=torch.from_numpy(smpl_poses[:, 0:1]).float(),
    body_pose=torch.from_numpy(smpl_poses[:, 1:]).float(),
    transl=torch.from_numpy(smpl_trans).float(),
    scaling=torch.from_numpy(smpl_scaling.reshape(1, 1)).float(),
    ).vertices.detach().numpy()
faces = smpl.faces

for verts in vertices:
  mesh = trimesh.Trimesh(verts, faces)
  mesh.visual.face_colors = [200, 200, 250, 100]
  vedo.show(mesh, interactive=False)
```

Unfortunately in our video we use blender and some other tools for visualization so we didn't release those in the repo. It's above lines should be a start for you to visualize the mesh!

Thanks
