### ISSUE TITLE
Where could I find the filter list of aistplusplus

### ISSUE THREAD

**Issue by icech** [google/aistplusplus_api#3]
Hi，thanks for sharing such a great dataset. I have downloaded the dataset but failed to find the ignore_list.txt which is mentioned in AIST++ websites ?

**Comment by Dongbox** [comment]
It's included in the annotation.

![image](https://user-images.githubusercontent.com/36894425/106443197-2eafd480-64b7-11eb-8641-b2450369fda6.png)

**Comment by icech** [comment]
Thanks a lot！
