### ISSUE TITLE
How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ?

### ISSUE THREAD

**Issue by zhangsanfeng86** [google/aistplusplus_api#31]
Hi @liruilong940607 ,
Thank you for your wonderful work! 

With the help of  smpl.forward().joints ,   'smpl_poses' and 'smpl_trans' conver to 'keypoints3d' .
But How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ?

**Comment by liruilong940607** [comment]
It is doable but non-trivial to convert keypoints3d to smpl parameters. You might want to look into Inverse Kinematics (example: https://github.com/CalciferZh/Minimal-IK) to do the job.
