### ISSUE TITLE
Visualization SMPL

### ISSUE THREAD

**Issue by fabienbaradel** [google/aistplusplus_api#6]
Hi,
Thanks a lot for releasing this dataset.
You are providing visualization of keypoints, that's great. However you are not providing a way to visualize SMPL from each camera view point, would it be possible to incorporate this in the ```run_vis.py``` file?
For the moment the SMPL poses is independant to camera viewpoints, how to you make it dependant from a specific camera viewpoint?
Thanks a lot for your help.
Fabien

**Comment by liruilong940607** [comment]
Hi Fabien,

We have provide code [here](https://github.com/google/aistplusplus_api/blob/main/demos/run_vis.py#L73) in `run_vis.py` to visualize SMPL in terms of body joints (keypoints) from each camera viewpoint. If you would like to instead visualize SMPL mesh, you would need use some renderer such as [this one](https://github.com/akanazawa/hmr/blob/da0ec4f150f515021a05fc8202299708e290447c/src/util/renderer.py#L23) with some modifications. 

Note that if you just want to project vertices on the SMPL body surface to image plane, you can always treat them in the same way you treat with body joints -- just apply the projection matrix to it like what we did in the `run_vis.py`

**Comment by fabienbaradel** [comment]
Hi @liruilong940607 ,
Thanks a lot for you feedback, that's very helpful.
To complete my issue I have another similar remark.
For the moment you are providing `keypoint3d` in world coordinates but I am interested to have these `keypoint3d` in camera coordinates for each of the camera. Would it be possible to provide a python script for doing this mapping? Is it possible to use the output of the [`crgoup`](https://github.com/google/aistplusplus_api/blob/main/demos/run_vis.py#L69) for having this information?

**Comment by liruilong940607** [comment]
Hi Febien,

Yes you can just use the `rotation` and `translation` of each camera to map the `keypoints3d` into camera coordinates:
`P' = [R | T] P`

**Comment by fabienbaradel** [comment]
Perfect, thanks a lot @liruilong940607 .
