### ISSUE TITLE
Audio fragments extraction/alignment

### ISSUE THREAD

**Issue by Qwinpin** [google/aistplusplus_api#7]
Hi,
Is it possible to post a script that aligned the music and motion recordings?
As I can see, in the AIST dataset the audio fragments do not match the length of the corresponding fragments, and when extracting audio directly from a video fragment it is not clear how to properly align the individual features of the audio and movement frames.

Timur Sokhin

**Comment by liruilong940607** [comment]
Hi Timur,

You can get a sense of how to process the audio from the code [here](https://github.com/liruilong940607/aistlib/blob/master/aistlib/processing.py#L21). That code will give you the audio features under 60 FPS which is frame-by-frame align with the motion / keypoints data in AIST++.

Note that repo is out of date. But for the audio processing part you can still refer to it.

**Comment by Qwinpin** [comment]
Great! Thank you
